### ISSUE TITLE
confirm compatibility with the latest python3 and update the readme

### ISSUE THREAD

**Issue by m040601** [rbarrois/inputexec#10]
Thanks for your work in this tool,

I have noticed the issue, https://github.com/rbarrois/inputexec/issues/1
but it talks about python 3.3, and the last update on this repo was on jun 2018.
Can you confirm that it is compatible with python 3.8 ?

If so, could you update the README ? It currently says:

> Installation
> inputexec is distributed under the 2-clause BSD license, and needs Python 2.6-3.3
> 

and that makes it confusing.

Some guy tried to install it with python 3.6 and this happened, https://gleichrichter.wordpress.com/2018/07/13/the-way-to-ir-sans-lirc/

> ... inputexec. .... looks very promising as it seems to target my usage case on the spot. But I fail to install the python script. First I get complains about UTF-8 problems and later some str – decode stuff. The first I fixed the simple way: Removing the UTF-8 chars. But the second one was above my current python capabilities. Probably that problem came with python 3.6 vs. 3.3. So inputexec gets dismissed......

With that clarified and the README polished, it would be easier  to create a package, for example for ArchLinux/AUR.

**Comment by rbarrois** [comment]
It's now compatible with the latest Python3 :)

Thanks for raising the issue, and sorry for the long delay.
For the record, I'm also using it on my system, with a Gentoo package: https://git.xelnor.net/?p=overlay.git;a=tree;f=app-misc/inputexec;hb=HEAD
