### ISSUE TITLE
Not working with Python3 ?

### ISSUE THREAD

**Issue by krei-se** [rbarrois/inputexec#12]
Thanks for this piece of software, i use it for bluetooth controls to mpc - had the same problem.

I use a config file and it outputs the correct keycodes - but doesn't seem to do anything. Is this a known problem with python3? Any way to debug the commands?

Thanks,

R

**Comment by rbarrois** [comment]
It seems to work perfectly fine for me, and that's the version I'm using 🤔

As a simple debugging test, have you tried running it with `--action-mode print`? It would show the keys it gets.

You could also run it with:
```sh
inputexec --source-file /dev/input/eventXX --logging-target stderr --logging-level debug
```

Let me know what kind of error you get — you may also paste your configuration here :)

**Comment by krei-se** [comment]
Thanks for getting back at me that fast, appreciate it. There is no "error" per se - it just doesn't do anything

From a user session:

```
[r@theresa ~]$ inputexec --source-file /dev/input/event4 --logging-level debug --logging-target stderr --action-commands inputexec.conf 
INFO inputexec.readers.evdev: Opened device /dev/input/event4 (MDR-ZX770BN (AVRCP))
INFO inputexec.cli: Starting loop.
INFO inputexec.readers.evdev: Grapping exclusive use of device /dev/input/event4, name "MDR-ZX770BN (AVRCP)", phys "00:e0:4c:01:04:4a"
DEBUG inputexec.readers.evdev: Skipping unhandled event event at 1675349430.338237, code 00, type 20, val 300
Traceback (most recent call last):
  File "/home/r/.local/lib/python3.10/site-packages/inputexec/readers/evdev.py", line 117, in convert_event
    return map_event(event)
  File "/home/r/.local/lib/python3.10/site-packages/inputexec/readers/evdev.py", line 65, in map_event
    raise UnhandledEvent("Unhandled evdev.InputEvent.type %d" % evdev_event.type)
inputexec.readers.evdev.UnhandledEvent: Unhandled evdev.InputEvent.type 20
keypress.KEY_PREVIOUSSONG
keypress.KEY_PREVIOUSSONG
keypress.KEY_NEXTSONG
keypress.KEY_PAUSECD


```
As you might guess /dev/input/event4 is readable by the user, i still tried as root, same result.

my inputexec.conf:

```
[commands]
keypress.KEY_PLAYCD = mpc play
keypress.KEY_PAUSECD = mpc pause
keypress.KEY_PREVIOUSSONG = mpc prev
keypress.KEY_NEXTSONG = mpc next
#keypress.KEY_STOPCD = mpc stop
#keypress.KEY_REWIND = mpc seekthrough -1%
#keypress.KEY_FASTFORWARD = mpc seekthrough +1%
```

i commented out the last 3 lines as i thought maybe the percentage-sign might cause the trouble?

all mpc commands work flawless if just typed out in console.

**Comment by krei-se** [comment]
OMG i got it to work, you need to pass `--action-mode run_sync` - its not a default. lol

Wonderful, finally i can control it from my headphones!!!!!

Thanks so much for your work!!!!

**Comment by rbarrois** [comment]
Great :) You can even put that in a configuration file, take a look at the `example.ini` one in the repository!
