### ISSUE TITLE
need to run a shell command on key press

### ISSUE THREAD

**Issue by seshugagan** [rbarrois/inputexec#4]
I need to run this command "sudo echo "pause" | telnet 127.0.0.1 9090" on a key press. I have included it in example.ini. It is giving an error "sudo: unable to resolve host max2play". 

I can run that command 
inputexec --action-commands=/usr/local/example.ini --source-file=/dev/input/by-path/platform-b0170000.i2c-platform-atc2603c-irkeypad.0-event-mouse --action-mode=run_sync 

manually on the terminal it is working fine. Could you please help.

**Comment by vrs01** [comment]
if it is working fine in the terminal, my suggestion is to put the command in a bash script and call the bash script with inputexec.

**Comment by seshugagan** [comment]
Thank you

**Comment by rbarrois** [comment]
Indeed, this suggestion is the best way to go here - inputexec does not parse the command line and won't interpret pipes.
