### ISSUE TITLE
Does shared mode could introduce some input latency

### ISSUE THREAD

**Issue by TiBeN** [rbarrois/inputexec#6]
Hi, 

First thanks for this good tool. 

I don't really know how evdev works internally and i wonder if using `inputexec` in shared mode could introduce some kind of input latency (or input lag) in others software using the device ?

Do you have some clues about that?

**Comment by rbarrois** [comment]
Hmm, I have no idea :(
I don't think it would create massive slowdowns, maybe a couple of milliseconds?

One would have to test it ;)

**Comment by TiBeN** [comment]
Thanks for answer

If i get some insights about this i'll report them here.
