### ISSUE TITLE
Does inputexec support of key combinations

### ISSUE THREAD

**Issue by TiBeN** [rbarrois/inputexec#7]
Hi, its me again with another question.

Does inputexec supports key combinations like "CTRL + SHIFT + F3" ?

**Comment by rbarrois** [comment]
Hey,

Sorry for the very late reply :/

Have you tried running inputexec in "print" mode to see how it displays a combination of keypresses?

**Comment by TiBeN** [comment]
Hi :) no worry.
I tried by the time but not sure your app support key combinations. I had some subtle needs too so i wrote my own small to feet them : [shortcutd](https://github.com/TiBeN/shortcutd). 
Thanks for reply.

**Comment by rbarrois** [comment]
Glad to hear it :)

I'm closing this since it's unlikely that I'll add it (don't need myself).
